// import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'
// import { ThemeProvider } from '@/components/theme-provider'
// import { Toaster } from 'react-hot-toast'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Fixora',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang='en' suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeProvider
//           attribute='class'
//           defaultTheme='system'
//           enableSystem
//           disableTransitionOnChange
//         >
//           <Toaster position='top-right' reverseOrder={false} />
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   )
// }
'use client'

import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from 'react-hot-toast'
import Navbar from '@/components/shared/Navbar'
import Footer from '@/components/shared/Footer'
import { usePathname } from 'next/navigation'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  // Only show Navbar/Footer for non-admin/vendor routes
  const showSharedLayout =
    !pathname.startsWith('/admin') &&
    !pathname.startsWith('/vendor') &&
    !pathname.startsWith('/customer')

  return (
    <html lang='en'>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position='top-right' reverseOrder={false} />
          {showSharedLayout && (
            <Navbar role='customer' isAuthenticated={true} />
          )}
          <main>{children}</main>
          {showSharedLayout && <Footer />}
        </ThemeProvider>
      </body>
    </html>
  )
}
