import type { Metadata } from 'next'

import Navbar from '../shared/Navbar'
import Footer from '../shared/Footer'
export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function CustomerLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <Navbar role='customer' isAuthenticated={true} />
      {children}
      <Footer />
    </html>
  )
}
