import type { Metadata } from 'next'

import Navbar from '../shared/Navbar'
import Footer from '../shared/Footer'
export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function VendorLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <section lang='en'>
      <Navbar role='vendor' isAuthenticated={true} />
      {children}
      <Footer />
    </section>
  )
}
